### ISSUE TITLE
Feature request: GitHub Action

### ISSUE THREAD

**Issue by tarlepp** [fabpot/local-php-security-checker#12]
It would be really nice, if there is official GitHub Action for this, so that we could use it easily within GitHub workflows.

**Comment by pplotka** [comment]
Hi! 

Maybe this is not official, but I created Docker image with go executable and a few moments ago I publish GitHub Actions: https://github.com/pplotka/local-php-security-checker-github-actions . I hope that my work will be helpful until official action is taken.

**Comment by fabpot** [comment]
https://github.com/symfonycorp/security-checker-action is now based on this repo.
