### ISSUE TITLE
Feature request: Homebrew package

### ISSUE THREAD

**Issue by kimpepper** [fabpot/local-php-security-checker#14]
It would be great to have a homebrew package to make it easier to install this on MacOS and Linux.

GoReleaser has built in support for this already: See https://goreleaser.com/customization/homebrew/

**Comment by VictorAvelar** [comment]
Can I take this one?

**Comment by fabpot** [comment]
@VictorAvelar Sure

**Comment by fabpot** [comment]
Closing as I'm going to archive this repository. Use `composer audit` instead.
