### ISSUE TITLE
What is the reason for changing the programming language from PHP to Go

### ISSUE THREAD

**Issue by WenkeChen** [fabpot/local-php-security-checker#29]
As I can see, there isn't too much calculation.

If you use PHP, we can manage this package via composer.

**Comment by mr-pmillz** [comment]
Because Go is awesome.

**Comment by ottaz** [comment]
@WenkeChen Try [enlightn's](https://github.com/enlightn/security-checker) checker.

**Comment by fabpot** [comment]
The main reason is that the server was written in Go for performance reasons (traffic was huge) and when I decided to open-source the code, I have extracted the server logic into this client.
