### ISSUE TITLE
Windows: the ANSI output is wrongly displayed

### ISSUE THREAD

**Issue by MircoBabin** [fabpot/local-php-security-checker#53]
I'm using Windows/10 latest version and cmd.exe as console. I downloaded https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.4/local-php-security-checker_2.0.4_windows_amd64.exe

Running this locally gives no ANSI output. But the window does support ANSI, as you can see by the Composer output and Laravel artisan output above.

I expect to see correct interpreted ansi escape sequences or, if that is not possible, a fallback to plain text. The output produced now is unreadable. I had to use `--format=json` to understand the output.

![image](https://user-images.githubusercontent.com/8981285/186905095-5d4783d1-29c5-4f70-be7e-77dcc0948d55.png)

**Comment by fabpot** [comment]
See #81
