### ISSUE TITLE
Add support for junit format

### ISSUE THREAD

**Issue by OxCom** [fabpot/local-php-security-checker#7]
Add [JUnit](https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_14.1.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html) report format to have proper [test reports with GitLab CI](https://git.ieee.uni-passau.de/help/ci/junit_test_reports.md)

**Comment by Seb33300** [comment]
This feature will also allow to use reports [with Bitbucket CI](https://support.atlassian.com/bitbucket-cloud/docs/test-reporting-in-pipelines/)
