### ISSUE TITLE
Q: is composer install required?

### ISSUE THREAD

**Issue by melroy89** [fabpot/local-php-security-checker#73]
I don't think a `composer install` is required to run this command, correct? Maybe explicitly say/document if it's required or not before executing `local-php-security-checker`.

**Comment by timstrawbridge** [comment]
Did you download the binary, rename it then make it executable? This happened to me when I first set it up on a project.

From the readme:
"Download a binary from the [Releases page on Github](https://github.com/fabpot/local-php-security-checker/releases), rename it to local-php-security-checker and make it executable."

**Comment by melroy89** [comment]
That was not my question/remark or problem. The question was whether `composer install` is required. I don't think so as fair as I can see. But I would be a welcome change to the README to add this. Especially in case where you want to add this command to the workflow/pipeline. 

Like I did here: https://github.com/MbinOrg/mbin/pull/226

**Comment by timstrawbridge** [comment]
No, composer install is not required.

**Comment by fabpot** [comment]
I think the readme is already very clear. That’s a Go project anyway, so no PHP involved.

**Comment by melroy89** [comment]
If it was clear I wasn't asking. You just maybe want to put somewhere that composer install isn't required or needed before running this checker.
