### ISSUE TITLE
Make it possible to download latest release

### ISSUE THREAD

**Issue by FractalizeR** [fabpot/local-php-security-checker#76]
GitHub supports downloading a file from a latest stable release via link like https://github.com/fabpot/local-php-security-checker/releases/latest/download/local-php-security-checker_1.2.0_linux_amd64. But due to filename in the assets containing a version, this is not currently possible.

**Comment by fabpot** [comment]
Done. See https://github.com/fabpot/local-php-security-checker/releases/tag/v2.1.0
