### ISSUE TITLE
Feature request: Publish a docker image

### ISSUE THREAD

**Issue by JoeAlamo** [fabpot/local-php-security-checker#8]
It would ease adoption if a docker image(s) was published whenever there was a new release of this tool.

**Comment by OxCom** [comment]
You can try this:
https://hub.docker.com/r/oxcom/php-security-checker

**Comment by St-Ex-savadenn** [comment]
Hello,

We have also built and published a docker image that is compatible with GitLab CI

https://gitlab.com/savadenn-public/runners/local-php-security-checker

**Comment by tehplague** [comment]
I'd definitively prefer an upstream-provided image if there was any.

**Comment by ivanovUA** [comment]
Added https://github.com/fabpot/local-php-security-checker/pull/15 for building docker image

**Comment by Basster** [comment]
As long as this is pending, I've created a pretty slim (~10MB) multi-arch (`amd64` & `arm64`) image over there at gitlab: https://gitlab.com/oroessner/local-php-security-checker-docker

**Comment by callain** [comment]
It would be nice to publish the image on dockerhub

**Comment by fabpot** [comment]
Closing as I'm going to archive this repository. Use `composer audit` instead.
